// Mocks generated by Mockito 5.0.10 from annotations
// in tada_chat/test/server_info_repository_settings_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tada_chat/datasources/server_info_data_source.dart' as _i3;
import 'package:tada_chat/model/server_info_response.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeServerInfoReponse<T> extends _i1.Fake
    implements _i2.ServerInfoReponse<T> {}

/// A class which mocks [ServerInfoDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockServerInfoDataSource extends _i1.Mock
    implements _i3.ServerInfoDataSource {
  MockServerInfoDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ServerInfoReponse<String>> getServerSettings() =>
      (super.noSuchMethod(Invocation.method(#getServerSettings, []),
              returnValue: Future<_i2.ServerInfoReponse<String>>.value(
                  _FakeServerInfoReponse<String>()))
          as _i4.Future<_i2.ServerInfoReponse<String>>);
  @override
  _i4.Future<_i2.ServerInfoReponse<String>> getMessagesHistory(
          String? roomName) =>
      (super.noSuchMethod(Invocation.method(#getMessagesHistory, [roomName]),
              returnValue: Future<_i2.ServerInfoReponse<String>>.value(
                  _FakeServerInfoReponse<String>()))
          as _i4.Future<_i2.ServerInfoReponse<String>>);
  @override
  _i4.Future<_i2.ServerInfoReponse<String>> getChatRooms() =>
      (super.noSuchMethod(Invocation.method(#getChatRooms, []),
              returnValue: Future<_i2.ServerInfoReponse<String>>.value(
                  _FakeServerInfoReponse<String>()))
          as _i4.Future<_i2.ServerInfoReponse<String>>);
}
